service: concert-owl
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  environment: ${file(env.yml)}


plugins:
  - serverless-offline

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /status
          method: get
  getShows:
    handler: index.dailyRunner
    events:
      - httpApi:
          path: /shows
          method: get
          
  pushDailySummary:
    handler: index.dailyRunner
    events:
      - schedule: cron(15 11 ? * * *)
  test:
    handler: index.test
    events:
      - httpApi:
          path: /test
          method: get  
